[package]
name = "random-client"
version = "0.1.0"
authors = ["ArturoAguilarL <arturo.aguilar@mercadolibre.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
rand = "0.8.4"